console.log(a);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
console.log(dsdgsgfgf);
var a = "greeting";